/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3b83e87005e0d64d62e3977084589bd5)
interface __BaseEnv_Env {
	CREDIT: R2Bucket;
	EASTMONEY: R2Bucket;
	LIABILITY_REPORT_SNAPSHOTS: R2Bucket;
	DB: D1Database;
	HYPERDRIVE: Hyperdrive;
	AUTHORIZATION_DB: Hyperdrive;
	CREDIT_SEARCH: AiSearchInstance;
	ASSETS: Fetcher;
	AUTH0_DOMAIN: "hasbai.eu.auth0.com";
	AUTH0_LOGIN_DOMAIN: "auth.hasbai.xyz";
	AUTH0_CLIENT_ID: "16vMxoYpr5AdPRiW1PkwIiHuRWszii6m";
	AUTH0_MANAGEMENT_CLIENT_ID: "LA46CcB3FQ4Uac4JyEzPSObcV4PV8CFU";
	ACCESS_MODE: "enforce";
	AUTHORIZATION_MODE: "beta-open";
	ACCESS_TEAM_DOMAIN: "hasbai.cloudflareaccess.com";
	ACCESS_AUD: "3eceddd7e32af3ce30d8209174e4ad8238fd9a27b700f1337fcff689a13fa973";
	CLOUDFLARE_ACCOUNT_ID: "5cecc63c78acf8f5473f8745f4244448";
	AI_GATEWAY_ID: "default";
	DATA_API_BASE_URL: "https://eastmoney.hasbai.xyz/data";
	CHOICE_DATA_API_URL: "https://eastmoney.hasbai.xyz/data";
	CF_AIG_TOKEN: string;
	AUTH0_MANAGEMENT_CLIENT_SECRET: string;
	CREDIT_AGENT: DurableObjectNamespace<import("agents").Agent<Cloudflare.Env>>;
	DATA: Service /* entrypoint InternalData from eastmoney-data */;
	BOND_LEDGER_IMPORT: Workflow<import("./src/lib/bond-ledger/types").BondLedgerImportParams>;
	ECONOMIC_INDICATOR_SYNC: Workflow<import("./src/lib/server/economic-indicator-sync").EconomicIndicatorSyncParams>;
	DEBT_IMPORT_WORKFLOW: Workflow<import("./src/lib/financing/debt-import-types").DebtImportWorkflowParams>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		durableNamespaces: "CreditAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AUTH0_DOMAIN" | "AUTH0_LOGIN_DOMAIN" | "AUTH0_CLIENT_ID" | "AUTH0_MANAGEMENT_CLIENT_ID" | "ACCESS_MODE" | "AUTHORIZATION_MODE" | "ACCESS_TEAM_DOMAIN" | "ACCESS_AUD" | "CLOUDFLARE_ACCOUNT_ID" | "AI_GATEWAY_ID" | "DATA_API_BASE_URL" | "CHOICE_DATA_API_URL" | "CF_AIG_TOKEN" | "AUTH0_MANAGEMENT_CLIENT_SECRET">> {}
}
