/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1b295fb7d2d5462c558e712c12c8643c)
interface __BaseEnv_Env {
	BOND_LEDGER: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	CLOUDFLARE_ACCOUNT_ID: "5cecc63c78acf8f5473f8745f4244448";
	AI_GATEWAY_ID: "default";
	DATA_API_BASE_URL: "https://eastmoney.hasbai.xyz/data";
	CF_AIG_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID" | "AI_GATEWAY_ID" | "DATA_API_BASE_URL" | "CF_AIG_TOKEN">> {}
}
