/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 56c7379591925ed4e5d66eb8b59c5070)
interface __BaseEnv_Env {
	CREDIT: R2Bucket;
	EASTMONEY: R2Bucket;
	LIABILITY_REPORT_SNAPSHOTS: R2Bucket;
	DB: D1Database;
	HYPERDRIVE: Hyperdrive;
	CREDIT_SEARCH: AiSearchInstance;
	ASSETS: Fetcher;
	CLOUDFLARE_ACCOUNT_ID: "5cecc63c78acf8f5473f8745f4244448";
	AI_GATEWAY_ID: "default";
	DATA_API_BASE_URL: "https://eastmoney.hasbai.xyz/data";
	CHOICE_DATA_API_URL: "https://eastmoney.hasbai.xyz/data";
	FROM_EMAIL: "no-reply@hasbai.xyz";
	MARKET_BRIEFING_RECIPIENTS: "shiyue@18.cn";
	CF_AIG_TOKEN: string;
	MARKET_BRIEFING_RESEND_API_KEY: string;
	CREDIT_AGENT: DurableObjectNamespace<import("agents").Agent<Cloudflare.Env>>;
	DATA: Service /* entrypoint InternalData from eastmoney-data */;
	IDENTITY: Service /* entrypoint IdentityService from eastmoney-gateway */;
	BOND_LEDGER_IMPORT: Workflow<import("./src/lib/bond-ledger/types").BondLedgerImportParams>;
	DEBT_IMPORT_WORKFLOW: Workflow<import("./src/lib/financing/debt-import-types").DebtImportWorkflowParams>;
	MARKET_BRIEFING: Workflow<import("./src/lib/market-briefing-types").MarketBriefingParams>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		durableNamespaces: "CreditAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CLOUDFLARE_ACCOUNT_ID" | "AI_GATEWAY_ID" | "DATA_API_BASE_URL" | "CHOICE_DATA_API_URL" | "FROM_EMAIL" | "MARKET_BRIEFING_RECIPIENTS" | "CF_AIG_TOKEN" | "MARKET_BRIEFING_RESEND_API_KEY">> {}
}
