import {test,expect} from '@playwright/test';
import {mockResources} from './fixtures.mjs';
import {creditFull} from './audit-fixtures.mjs';

test('desktop credit weekly report presents nonempty news and five product details',async({page},testInfo)=>{
 test.skip(testInfo.project.name!=='desktop','Desktop UI audit');
 await mockResources(page);await page.route('**/api/credit**',route=>route.fulfill({json:creditFull}));
 await page.setViewportSize({width:1280,height:900});await page.goto('/credit-workbench/weekly');
 await expect(page.getByRole('region',{name:'本周授信快讯',exact:true})).toContainText('较前额增加5亿');
 await expect(page.getByRole('table',{name:'所选报表日前近6个月新增、续作和扩额授信批复',exact:true})).toContainText('同业拆借 3.00亿');
 await expect(page.locator('.tr-workspace')).toHaveScreenshot('credit-weekly-full-desktop.png');
});

test('desktop credit metrics and expanded records stay within the workspace',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop','Desktop UI audit');
  await mockResources(page);
  await page.route('**/api/credit**',route=>route.fulfill({json:creditFull}));
  await page.setViewportSize({width:1280,height:900});
  await page.goto('/credit-workbench');
  await expect(page.getByRole('rowheader',{name:'银行甲',exact:true})).toBeVisible();
  const metrics=page.getByRole('region',{name:'授信总览',exact:true});
  const tops=await metrics.getByRole('article').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().y));
  expect(Math.max(...tops)-Math.min(...tops)).toBeLessThanOrEqual(1);
  const region=page.getByRole('region',{name:'授信机构记录',exact:true});
  const bounds=await region.evaluate(el=>({width:el.clientWidth,content:el.scrollWidth}));
  expect(bounds.content).toBeLessThanOrEqual(bounds.width+1);
  await page.getByRole('combobox',{name:'授信风险',exact:true}).selectOption('expiry');
  await expect(region.getByRole('rowheader',{name:'银行乙',exact:true})).toHaveCount(0);
  await region.getByRole('button',{name:'详情',exact:true}).click();
  await expect(region).toHaveJSProperty('scrollLeft',0);
  await expect(region.getByRole('textbox',{name:'机构性质',exact:true})).toHaveValue('商业银行');
  const products=await region.getByRole('group').evaluateAll(nodes=>nodes.map(n=>n.getBoundingClientRect().y));
  expect(products).toHaveLength(5);
  expect(Math.max(...products)-Math.min(...products)).toBeLessThanOrEqual(1);
  await page.setViewportSize({width:1280,height:1600});
  await region.evaluate(el=>el.scrollIntoView({block:'center',inline:'nearest',behavior:'instant'}));await expect(region).toBeInViewport({ratio:1});
  await expect(region).toHaveScreenshot('credit-record-expanded.png');
  await page.setViewportSize({width:1280,height:900});
  await region.getByRole('button',{name:'收起',exact:true}).click();
  await expect(region.getByRole('textbox',{name:'机构性质',exact:true})).toHaveCount(0);
  await page.getByRole('combobox',{name:'授信风险',exact:true}).selectOption('all');
  await expect(region.getByRole('rowheader',{name:'银行乙',exact:true})).toBeVisible();
});

test('credit application presents distinct operations while the overview stays read only',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='desktop','Desktop credit application');
  await mockResources(page);
  await page.route('**/api/credit**',route=>route.fulfill({json:creditFull}));
  await page.setViewportSize({width:1280,height:900});
  await page.goto('/credit-workbench');
  const region=page.getByRole('region',{name:'授信机构记录',exact:true});
  await region.getByRole('button',{name:'详情',exact:true}).first().click();
  await expect(region.getByRole('textbox',{name:'机构性质',exact:true})).toHaveAttribute('readonly');
  await page.getByRole('button',{name:'授信申请',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'授信申请'});
  await expect(dialog.getByRole('textbox',{name:'机构名称'})).toBeVisible();
  await dialog.getByRole('button',{name:'续期',exact:true}).click();
  await expect(dialog.getByLabel('新到期日')).toBeVisible();
  await expect(dialog.getByRole('textbox',{name:'机构名称'})).toHaveCount(0);
  await dialog.getByRole('button',{name:'扩额',exact:true}).click();
  await expect(dialog.getByRole('spinbutton',{name:'扩额后总额（亿元）'})).toBeVisible();
  await dialog.getByRole('button',{name:'撤销',exact:true}).click();
  await expect(dialog.getByRole('checkbox',{name:'确认撤销该机构授信'})).toBeVisible();
  await dialog.getByRole('button',{name:'维护',exact:true}).click();
  await expect(dialog.getByRole('spinbutton',{name:'二级买卖净余额（亿元）'})).toBeVisible();
  await dialog.getByRole('button',{name:'新增',exact:true}).click();
  await expect(dialog.getByRole('textbox',{name:'机构名称'})).toBeVisible();
  await expect(dialog).toHaveCSS('opacity','1');
  await expect(dialog).toHaveScreenshot('credit-application-new.png');
});
