import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { installDom, loadComponent } from './svelte-dom.mjs';
const window = installDom();
const { mount, unmount, flushSync, tick } = await import('svelte');
const { globalMessages } = await import('../../src/lib/global-messages.ts');
const { PERMISSION_CODES } = await import('../../src/lib/permissions.ts');
const submissions = globalThis.permissionSubmissions = [];
globalThis.fetch = async () => Response.json({user:null,account:null});
const source = (await readFile(new URL('../../src/routes/management/people/+page.svelte', import.meta.url),'utf8')).replace("import { enhance } from '$app/forms';", `
function enhance(node, handler) {
  const submit = event => { event.preventDefault(); const complete = handler({formElement:node}); globalThis.permissionSubmissions.push({ data:new window.FormData(node), complete }); };
  node.addEventListener('submit', submit);
  return {destroy(){node.removeEventListener('submit',submit)}};
}`);
const Page = await loadComponent('src/routes/management/people/+page.svelte', source);
const app = mount(Page,{target:document.body,props:{data:{roles:[{id:'rol_A',name:'测试管理员',description:''},{id:'rol_B',name:'测试成员',description:''}],configurations:{rol_A:{permissions:[],version:'a'.repeat(64)},rol_B:{permissions:[],version:'b'.repeat(64)}},permissions:['auth.permission:update'],mode:'beta-open'}}});
flushSync();
assert.ok(document.querySelector('.alert-info').textContent.includes('内测全开放'));
const roleButtons=()=>[...document.querySelectorAll('.role-list button')];
const firstPermission=()=>document.querySelector('.permission-item input');
flushSync(()=>firstPermission().click());
assert.equal(document.querySelector('input[name="permissions"]').value,PERMISSION_CODES[0]);
flushSync(()=>roleButtons()[1].click());
assert.equal(firstPermission().checked,false);
flushSync(()=>roleButtons()[0].click());
assert.equal(firstPermission().checked,true,'switching roles preserves unsaved drafts');
const form=document.querySelector('.permission-editor form');
flushSync(()=>form.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true})));
assert.equal(submissions.length,1);
assert.equal(submissions[0].data.get('roleId'),'rol_A');
assert.equal(roleButtons()[0].disabled,true);
await submissions[0].complete({result:{type:'failure',data:{message:'并发冲突'}},update:async()=>{throw new Error('failed save must preserve local state')}});
flushSync();
assert.equal(firstPermission().checked,true,'failed save preserves checkbox selection');
assert.equal(roleButtons()[0].disabled,false);
flushSync(()=>form.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true})));
await submissions[1].complete({result:{type:'success',data:{roleId:'rol_A',configuration:{permissions:[PERMISSION_CODES[0]],version:'c'.repeat(64)},message:'已保存'}},update:async()=>{}});
flushSync();
assert.equal(document.querySelector('.permission-save').disabled,true);
assert.equal(document.querySelector('input[name="version"]').value,'c'.repeat(64));
await unmount(app);
globalMessages.clear();

const AccountHost=await loadComponent('tests/helpers/AccountHost.svelte',`<script>
import {setContext} from 'svelte';
import AuthMenu from '../../src/lib/AuthMenu.svelte';
let account=$state({name:'测试人员',department:'资金管理部'});
setContext('site-account',()=>account);
export function rename(){account={name:'新姓名',department:'资金管理部'}};
</script><AuthMenu />`);
const accountApp=mount(AccountHost,{target:document.body});flushSync();
assert.equal(document.querySelectorAll('a').length,1);
assert.equal(document.querySelector('a').getAttribute('href'),'/profile');
assert.match(document.querySelector('a').textContent,/测试人员\s*\/\s*资金管理部/);
assert.ok(document.querySelector('a svg'));
assert.equal(document.querySelector('[href="/management"]'),null);
flushSync(()=>accountApp.rename());assert.match(document.querySelector('a').textContent,/新姓名/);
await unmount(accountApp);

const Filter=await loadComponent('src/lib/financing/MultiSelectFilter.svelte');
const filterApp=mount(Filter,{target:document.body,props:{label:'负债品种',options:['固定收益凭证','公司债'],values:[],allLabel:'全部品种',optionLabels:{'固定收益凭证':'固收'}}});flushSync();
const details=document.querySelector('details');details.open=true;
flushSync(()=>document.querySelector('input[type="checkbox"]').click());
assert.match(document.querySelector('summary').textContent,/固收/);
window.dispatchEvent(new window.KeyboardEvent('keydown',{key:'Escape'}));
assert.equal(details.open,false);
assert.equal(document.activeElement,document.querySelector('summary'));
details.open=true;
flushSync(()=>document.querySelector('.filter-popover button').click());
assert.match(document.querySelector('summary').textContent,/全部品种/);
assert.ok([...document.querySelectorAll('input')].every(input=>!input.checked));
await unmount(filterApp);await tick();await window.happyDOM.abort();
console.log('Management and account interaction checks passed');
